version: '3.7'
services:
  seniorcare_php:
    container_name: seniorcare_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      COMPOSER_MEMORY_LIMIT: -1
    expose:
      - 9000
    networks:
      - seniorcare

  seniorcare_nginx:
    container_name: seniorcare_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./nginx/logs:/var/log/nginx
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      # SSL
      - 443:443
      # SSL
      - 80:80
    networks:
      - seniorcare

  seniorcare_db:
    container_name: seniorcare_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - seniorcare_database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=testing,${DB_DATABASE:-base}
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - LC_ALL=C.UTF-8
    networks:
      - seniorcare

  seniorcare_keydb:
    container_name: seniorcare_keydb
    build:
      context: ./docker/keydb
      dockerfile: Dockerfile
    volumes:
      - seniorcare_keydb_volume:/data
    ports:
      - "6379:6379"
    networks:
      - seniorcare

  seniorcare_mailhog:
    container_name: seniorcare_mailhog
    build:
      context: ./docker/mailhog
      dockerfile: Dockerfile
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - seniorcare

  # PgAdmin container
  pgadmin:
    container_name: seniorcare_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - seniorcare_pgadmin_volume:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - seniorcare

volumes:
  seniorcare_database_volume:
    driver: local
  seniorcare_keydb_volume:
    driver: local
  seniorcare_pgadmin_volume:
    driver: local

networks:
  seniorcare:
